/**
 * Mapping of well-known tech hubs and major global cities to their countries.
 * This is intentionally focused on startup/tech ecosystems and can be extended easily.
 * Keys are stored in lowercase for case-insensitive lookup.
 */

export const CITY_COUNTRY_MAP: Record<string, string> = {
  // North America
  "san francisco": "United States",
  "san francisco bay area": "United States",
  "san jose": "United States",
  "silicon valley": "United States",
  "new york": "United States",
  "new york city": "United States",
  "los angeles": "United States",
  "seattle": "United States",
  "boston": "United States",
  "austin": "United States",
  "chicago": "United States",
  "denver": "United States",
  "atlanta": "United States",
  "miami": "United States",
  "dallas": "United States",
  "houston": "United States",
  "washington": "United States",
  "philadelphia": "United States",
  "san diego": "United States",
  "toronto": "Canada",
  "vancouver": "Canada",
  "montreal": "Canada",
  "ottawa": "Canada",
  "calgary": "Canada",
  "mexico city": "Mexico",
  "guadalajara": "Mexico",

  // Europe
  "london": "United Kingdom",
  "manchester": "United Kingdom",
  "edinburgh": "United Kingdom",
  "dublin": "Ireland",
  "paris": "France",
  "lyon": "France",
  "berlin": "Germany",
  "munich": "Germany",
  "hamburg": "Germany",
  "frankfurt": "Germany",
  "cologne": "Germany",
  "amsterdam": "Netherlands",
  "rotterdam": "Netherlands",
  "the hague": "Netherlands",
  "brussels": "Belgium",
  "antwerp": "Belgium",
  "luxembourg": "Luxembourg",
  "madrid": "Spain",
  "barcelona": "Spain",
  "valencia": "Spain",
  "lisbon": "Portugal",
  "porto": "Portugal",
  "rome": "Italy",
  "milan": "Italy",
  "turin": "Italy",
  "stockholm": "Sweden",
  "gothenburg": "Sweden",
  "oslo": "Norway",
  "bergen": "Norway",
  "helsinki": "Finland",
  "copenhagen": "Denmark",
  "aarhus": "Denmark",
  "tallinn": "Estonia",
  "vilnius": "Lithuania",
  "riga": "Latvia",
  "warsaw": "Poland",
  "krakow": "Poland",
  "prague": "Czech Republic",
  "vienna": "Austria",
  "budapest": "Hungary",
  "bucharest": "Romania",
  "sofia": "Bulgaria",
  "athens": "Greece",
  "zurich": "Switzerland",
  "geneva": "Switzerland",

  // Middle East & Africa
  "tel aviv": "Israel",
  "jerusalem": "Israel",
  "dubai": "United Arab Emirates",
  "abu dhabi": "United Arab Emirates",
  "doha": "Qatar",
  "riyadh": "Saudi Arabia",
  "jeddah": "Saudi Arabia",
  "istanbul": "Turkey",
  "ankara": "Turkey",
  "cairo": "Egypt",
  "lagos": "Nigeria",
  "nairobi": "Kenya",
  "johannesburg": "South Africa",
  "cape town": "South Africa",

  // Asia-Pacific
  "singapore": "Singapore",
  "hong kong": "Hong Kong",
  "shanghai": "China",
  "beijing": "China",
  "shenzhen": "China",
  "guangzhou": "China",
  "tokyo": "Japan",
  "osaka": "Japan",
  "seoul": "South Korea",
  "busan": "South Korea",
  "taipei": "Taiwan",
  "bangkok": "Thailand",
  "kuala lumpur": "Malaysia",
  "jakarta": "Indonesia",
  "manila": "Philippines",
  "ho chi minh city": "Vietnam",
  "hanoi": "Vietnam",
  "mumbai": "India",
  "delhi": "India",
  "new delhi": "India",
  "bengaluru": "India",
  "bangalore": "India",
  "hyderabad": "India",
  "chennai": "India",
  "pune": "India",
  "kolkata": "India",
  "islamabad": "Pakistan",
  "lahore": "Pakistan",
  "karachi": "Pakistan",
  "sydney": "Australia",
  "melbourne": "Australia",
  "brisbane": "Australia",
  "perth": "Australia",
  "auckland": "New Zealand",
  "wellington": "New Zealand",

  // Latin America
  "sao paulo": "Brazil",
  "rio de janeiro": "Brazil",
  "belo horizonte": "Brazil",
  "brasilia": "Brazil",
  "santiago": "Chile",
  "valparaiso": "Chile",
  "buenos aires": "Argentina",
  "cordoba": "Argentina",
  "montevideo": "Uruguay",
  "bogota": "Colombia",
  "medellin": "Colombia",
  "lima": "Peru",
  "quito": "Ecuador",
};

export function getCountryForCity(city?: string | null): string | null {
  if (!city) return null;
  const normalized = city.trim().toLowerCase();
  return CITY_COUNTRY_MAP[normalized] || null;
}

